packages:
  - "examples/*"
  - "packages/*"
  - "lib"
  - "scripts"
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  pre-commit: true
  sharp: true
minimumReleaseAgeExclude:
  - '@next/swc-win32-x64-msvc@16.3.5'
