/** KaTeX v0.16.22 — regenerate via `pnpm generate:katex` (fetches from https://raw.githubusercontent.com/KaTeX/KaTeX/v0.16.22/src). */
export const KATEX_SYMBOLS: Record<string, string> = {
  " ": " ",
  _: "_",
  "-": "−",
  "--": "–",
  "---": "—",
  ",": ",",
  ";": ";",
  ":": ":",
  "!": "!",
  "?": "?",
  ".": "˙",
  "'": "’",
  "''": "”",
  "{": "{",
  "}": "}",
  "@cdots": "⋯",
  "@gvertneqq": "",
  "@imath": "",
  "@jmath": "",
  "@llcorner": "└",
  "@lrcorner": "┘",
  "@lvertneqq": "",
  "@ngeqq": "",
  "@ngeqslant": "",
  "@nleqq": "",
  "@nleqslant": "",
  "@not": "",
  "@nshortmid": "",
  "@nshortparallel": "",
  "@nsubseteqq": "",
  "@nsupseteqq": "",
  "@ulcorner": "┌",
  "@urcorner": "┐",
  "@varsubsetneq": "",
  "@varsubsetneqq": "",
  "@varsupsetneq": "",
  "@varsupsetneqq": "",
  "*": "∗",
  "&": "&",
  "#": "#",
  "%": "%",
  "`": "‘",
  "``": "“",
  "^": "ˆ",
  "+": "+",
  "=": "ˉ",
  "|": "∥",
  "~": "˜",
  $: "$",
  acute: "ˊ",
  ae: "æ",
  AE: "Æ",
  alef: "ℵ",
  alefsym: "ℵ",
  aleph: "ℵ",
  alpha: "α",
  amalg: "⨿",
  And: "&",
  angle: "∠",
  approx: "≈",
  approxeq: "≊",
  ast: "∗",
  asymp: "≍",
  backepsilon: "∍",
  backprime: "‵",
  backsim: "∽",
  backsimeq: "⋍",
  backslash: "\\",
  bar: "ˉ",
  barwedge: "⊼",
  because: "∵",
  beta: "β",
  beth: "ℶ",
  between: "≬",
  bgroup: "{",
  bigcap: "⋂",
  bigcirc: "◯",
  bigcup: "⋃",
  bigodot: "⨀",
  bigoplus: "⨁",
  bigotimes: "⨂",
  bigsqcup: "⨆",
  bigstar: "★",
  bigtriangledown: "▽",
  bigtriangleup: "△",
  biguplus: "⨄",
  bigvee: "⋁",
  bigwedge: "⋀",
  blacklozenge: "⧫",
  blacksquare: "■",
  blacktriangle: "▲",
  blacktriangledown: "▼",
  blacktriangleleft: "◀",
  blacktriangleright: "▶",
  bot: "⊥",
  bowtie: "⋈",
  Box: "□",
  boxdot: "⊡",
  boxminus: "⊟",
  boxplus: "⊞",
  boxtimes: "⊠",
  breve: "˘",
  bull: "∙",
  bullet: "∙",
  bumpeq: "≏",
  Bumpeq: "≎",
  c: "¸",
  cap: "∩",
  Cap: "⋒",
  cdot: "⋅",
  cdotp: "⋅",
  cdots: "⋯",
  centerdot: "⋅",
  check: "ˇ",
  checkmark: "✓",
  chi: "χ",
  circ: "∘",
  circeq: "≗",
  circlearrowleft: "↺",
  circlearrowright: "↻",
  circledast: "⊛",
  circledcirc: "⊚",
  circleddash: "⊝",
  circledR: "®",
  circledS: "Ⓢ",
  clubs: "♣",
  clubsuit: "♣",
  coloneqq: "≔",
  Coloneqq: "⩴",
  complement: "∁",
  cong: "≅",
  coprod: "∐",
  copyright: "©",
  cup: "∪",
  Cup: "⋓",
  curlyeqprec: "⋞",
  curlyeqsucc: "⋟",
  curlyvee: "⋎",
  curlywedge: "⋏",
  curvearrowleft: "↶",
  curvearrowright: "↷",
  dag: "†",
  dagger: "†",
  Dagger: "‡",
  daleth: "ℸ",
  darr: "↓",
  dArr: "⇓",
  Darr: "⇓",
  dashleftarrow: "⇠",
  dashrightarrow: "⇢",
  dashv: "⊣",
  dblcolon: "∷",
  ddag: "‡",
  ddagger: "‡",
  ddot: "¨",
  ddots: "⋱",
  degree: "°",
  delta: "δ",
  Delta: "Δ",
  diagdown: "╲",
  diagup: "╱",
  diamond: "⋄",
  Diamond: "◊",
  diamonds: "♢",
  diamondsuit: "♢",
  digamma: "ϝ",
  div: "÷",
  divideontimes: "⋇",
  dot: "˙",
  doteq: "≐",
  Doteq: "≑",
  doteqdot: "≑",
  dotplus: "∔",
  doublebarwedge: "⩞",
  doublecap: "⋒",
  doublecup: "⋓",
  downarrow: "↓",
  Downarrow: "⇓",
  downdownarrows: "⇊",
  downharpoonleft: "⇃",
  downharpoonright: "⇂",
  egroup: "}",
  ell: "ℓ",
  empty: "∅",
  emptyset: "∅",
  epsilon: "ϵ",
  eqcirc: "≖",
  eqcolon: "∹",
  eqqcolon: "≕",
  eqsim: "≂",
  eqslantgtr: "⪖",
  eqslantless: "⪕",
  equiv: "≡",
  eta: "η",
  eth: "ð",
  exist: "∃",
  exists: "∃",
  fallingdotseq: "≒",
  Finv: "Ⅎ",
  flat: "♭",
  forall: "∀",
  frown: "⌢",
  Game: "⅁",
  gamma: "γ",
  Gamma: "Γ",
  ge: "≥",
  geq: "≥",
  geqq: "≧",
  geqslant: "⩾",
  gets: "←",
  gg: "≫",
  ggg: "⋙",
  gggtr: "⋙",
  gimel: "ℷ",
  gnapprox: "⪊",
  gneq: "⪈",
  gneqq: "≩",
  gnsim: "⋧",
  grave: "ˋ",
  gt: ">",
  gtrapprox: "⪆",
  gtrdot: "⋗",
  gtreqless: "⋛",
  gtreqqless: "⪌",
  gtrless: "≷",
  gtrsim: "≳",
  H: "˝",
  harr: "↔",
  hArr: "⇔",
  Harr: "⇔",
  hat: "^",
  hbar: "ℏ",
  hearts: "♡",
  heartsuit: "♡",
  hookleftarrow: "↩",
  hookrightarrow: "↪",
  hslash: "ℏ",
  i: "ı",
  iiint: "∭",
  iint: "∬",
  Im: "ℑ",
  image: "ℑ",
  imageof: "⊷",
  in: "∈",
  infin: "∞",
  infty: "∞",
  int: "∫",
  intercal: "⊺",
  intop: "∫",
  iota: "ι",
  isin: "∈",
  j: "ȷ",
  Join: "⋈",
  kappa: "κ",
  lambda: "λ",
  Lambda: "Λ",
  land: "∧",
  lang: "⟨",
  langle: "⟨",
  larr: "←",
  lArr: "⇐",
  Larr: "⇐",
  lbrace: "{",
  lBrace: "⦃",
  lbrack: "[",
  lceil: "⌈",
  ldotp: ".",
  ldots: "…",
  le: "≤",
  leadsto: "⇝",
  leftarrow: "←",
  Leftarrow: "⇐",
  leftarrowtail: "↢",
  leftharpoondown: "↽",
  leftharpoonup: "↼",
  leftleftarrows: "⇇",
  leftrightarrow: "↔",
  Leftrightarrow: "⇔",
  leftrightarrows: "⇆",
  leftrightharpoons: "⇋",
  leftrightsquigarrow: "↭",
  leftthreetimes: "⋋",
  leq: "≤",
  leqq: "≦",
  leqslant: "⩽",
  lessapprox: "⪅",
  lessdot: "⋖",
  lesseqgtr: "⋚",
  lesseqqgtr: "⪋",
  lessgtr: "≶",
  lesssim: "≲",
  lfloor: "⌊",
  lgroup: "⟮",
  lhd: "⊲",
  ll: "≪",
  llbracket: "⟦",
  llcorner: "⌞",
  Lleftarrow: "⇚",
  lll: "⋘",
  llless: "⋘",
  lmoustache: "⎰",
  lnapprox: "⪉",
  lneq: "⪇",
  lneqq: "≨",
  lnot: "¬",
  lnsim: "⋦",
  longleftarrow: "⟵",
  Longleftarrow: "⟸",
  longleftrightarrow: "⟷",
  Longleftrightarrow: "⟺",
  longmapsto: "⟼",
  longrightarrow: "⟶",
  Longrightarrow: "⟹",
  looparrowleft: "↫",
  looparrowright: "↬",
  lor: "∨",
  lozenge: "◊",
  lparen: "(",
  lq: "`",
  lrarr: "↔",
  lrArr: "⇔",
  Lrarr: "⇔",
  lrcorner: "⌟",
  Lsh: "↰",
  lt: "<",
  ltimes: "⋉",
  lvert: "∣",
  lVert: "∥",
  maltese: "✠",
  mapsto: "↦",
  mathellipsis: "…",
  mathring: "˚",
  mathsterling: "£",
  measuredangle: "∡",
  medspace: ":",
  mho: "℧",
  mid: "∣",
  models: "⊨",
  mp: "∓",
  mu: "μ",
  multimap: "⊸",
  nabla: "∇",
  natural: "♮",
  ncong: "≆",
  ne: "≠",
  nearrow: "↗",
  neg: "¬",
  negthinspace: "!",
  neq: "≠",
  nexists: "∄",
  ngeq: "≱",
  ngtr: "≯",
  ni: "∋",
  nleftarrow: "↚",
  nLeftarrow: "⇍",
  nleftrightarrow: "↮",
  nLeftrightarrow: "⇎",
  nleq: "≰",
  nless: "≮",
  nmid: "∤",
  nobreakspace: " ",
  notin: "∉",
  notni: "∌",
  nparallel: "∦",
  nprec: "⊀",
  npreceq: "⋠",
  nrightarrow: "↛",
  nRightarrow: "⇏",
  nsim: "≁",
  nsubseteq: "⊈",
  nsucc: "⊁",
  nsucceq: "⋡",
  nsupseteq: "⊉",
  ntriangleleft: "⋪",
  ntrianglelefteq: "⋬",
  ntriangleright: "⋫",
  ntrianglerighteq: "⋭",
  nu: "ν",
  nvdash: "⊬",
  nvDash: "⊭",
  nVdash: "⊮",
  nVDash: "⊯",
  nwarrow: "↖",
  o: "ø",
  O: "Ø",
  odot: "⊙",
  oe: "œ",
  OE: "Œ",
  oiiint: "∰",
  oiint: "∯",
  oint: "∮",
  omega: "ω",
  Omega: "Ω",
  omicron: "ο",
  ominus: "⊖",
  oplus: "⊕",
  ordinarycolon: ":",
  origof: "⊶",
  oslash: "⊘",
  otimes: "⊗",
  owns: "∋",
  P: "¶",
  parallel: "∥",
  partial: "∂",
  perp: "⊥",
  phi: "ϕ",
  Phi: "Φ",
  pi: "π",
  Pi: "Π",
  pitchfork: "⋔",
  plusmn: "±",
  pm: "±",
  pounds: "£",
  prec: "≺",
  precapprox: "⪷",
  preccurlyeq: "≼",
  preceq: "⪯",
  precnapprox: "⪹",
  precneqq: "⪵",
  precnsim: "⋨",
  precsim: "≾",
  prime: "′",
  prod: "∏",
  propto: "∝",
  psi: "ψ",
  Psi: "Ψ",
  qquad: "  ",
  quad: " ",
  r: "˚",
  rang: "⟩",
  rangle: "⟩",
  rarr: "→",
  rArr: "⇒",
  Rarr: "⇒",
  rbrace: "}",
  rBrace: "⦄",
  rbrack: "]",
  rceil: "⌉",
  Re: "ℜ",
  real: "ℜ",
  restriction: "↾",
  rfloor: "⌋",
  rgroup: "⟯",
  rhd: "⊳",
  rho: "ρ",
  rightarrow: "→",
  Rightarrow: "⇒",
  rightarrowtail: "↣",
  rightharpoondown: "⇁",
  rightharpoonup: "⇀",
  rightleftarrows: "⇄",
  rightleftharpoons: "⇌",
  rightrightarrows: "⇉",
  rightsquigarrow: "⇝",
  rightthreetimes: "⋌",
  risingdotseq: "≓",
  rmoustache: "⎱",
  rparen: ")",
  rq: "'",
  rrbracket: "⟧",
  Rrightarrow: "⇛",
  Rsh: "↱",
  rtimes: "⋊",
  rvert: "∣",
  rVert: "∥",
  S: "§",
  sdot: "⋅",
  searrow: "↘",
  sect: "§",
  setminus: "∖",
  sharp: "♯",
  shortmid: "∣",
  shortparallel: "∥",
  sigma: "σ",
  Sigma: "Σ",
  sim: "∼",
  simeq: "≃",
  smallfrown: "⌢",
  smallint: "∫",
  smallsetminus: "∖",
  smallsmile: "⌣",
  smile: "⌣",
  space: " ",
  spades: "♠",
  spadesuit: "♠",
  sphericalangle: "∢",
  sqcap: "⊓",
  sqcup: "⊔",
  sqsubset: "⊏",
  sqsubseteq: "⊑",
  sqsupset: "⊐",
  sqsupseteq: "⊒",
  square: "□",
  ss: "ß",
  star: "⋆",
  sub: "⊂",
  sube: "⊆",
  subset: "⊂",
  Subset: "⋐",
  subseteq: "⊆",
  subseteqq: "⫅",
  subsetneq: "⊊",
  subsetneqq: "⫋",
  succ: "≻",
  succapprox: "⪸",
  succcurlyeq: "≽",
  succeq: "⪰",
  succnapprox: "⪺",
  succneqq: "⪶",
  succnsim: "⋩",
  succsim: "≿",
  sum: "∑",
  supe: "⊇",
  supset: "⊃",
  Supset: "⋑",
  supseteq: "⊇",
  supseteqq: "⫆",
  supsetneq: "⊋",
  supsetneqq: "⫌",
  surd: "√",
  swarrow: "↙",
  tau: "τ",
  textasciicircum: "^",
  textasciitilde: "~",
  textbackslash: "\\",
  textbar: "|",
  textbardbl: "∥",
  textbraceleft: "{",
  textbraceright: "}",
  textcircled: "◯",
  textdagger: "†",
  textdaggerdbl: "‡",
  textdegree: "°",
  textdollar: "$",
  textellipsis: "…",
  textemdash: "—",
  textendash: "–",
  textgreater: ">",
  textless: "<",
  textquotedblleft: "“",
  textquotedblright: "”",
  textquoteleft: "‘",
  textquoteright: "’",
  textregistered: "®",
  textsterling: "£",
  textunderscore: "_",
  therefore: "∴",
  theta: "θ",
  Theta: "Θ",
  thetasym: "ϑ",
  thickapprox: "≈",
  thicksim: "∼",
  thickspace: ";",
  thinspace: ",",
  tilde: "~",
  times: "×",
  to: "→",
  top: "⊤",
  triangle: "△",
  triangledown: "▽",
  triangleleft: "◃",
  trianglelefteq: "⊴",
  triangleq: "≜",
  triangleright: "▹",
  trianglerighteq: "⊵",
  twoheadleftarrow: "↞",
  twoheadrightarrow: "↠",
  u: "˘",
  u00f0: "ð",
  u0131: "ı",
  u0237: "ȷ",
  u0391: "A",
  u0392: "B",
  u0395: "E",
  u0396: "Z",
  u0397: "H",
  u0399: "I",
  u039A: "K",
  u039C: "M",
  u039D: "N",
  u039F: "O",
  u03A1: "P",
  u03A4: "T",
  u03A7: "X",
  u2102: "C",
  u210D: "H",
  u210E: "h",
  u2115: "N",
  u2119: "P",
  u211A: "Q",
  u211D: "R",
  u2124: "Z",
  uarr: "↑",
  uArr: "⇑",
  Uarr: "⇑",
  ulcorner: "⌜",
  unlhd: "⊴",
  unrhd: "⊵",
  uparrow: "↑",
  Uparrow: "⇑",
  updownarrow: "↕",
  Updownarrow: "⇕",
  upharpoonleft: "↿",
  upharpoonright: "↾",
  uplus: "⊎",
  upsilon: "υ",
  Upsilon: "Υ",
  upuparrows: "⇈",
  urcorner: "⌝",
  v: "ˇ",
  varepsilon: "ε",
  varkappa: "ϰ",
  varnothing: "∅",
  varphi: "φ",
  varpi: "ϖ",
  varpropto: "∝",
  varrho: "ϱ",
  varsigma: "ς",
  vartheta: "ϑ",
  vartriangle: "△",
  vartriangleleft: "⊲",
  vartriangleright: "⊳",
  varvdots: "⋮",
  vdash: "⊢",
  vDash: "⊨",
  Vdash: "⊩",
  vdots: "⋮",
  vec: "⃗",
  vee: "∨",
  veebar: "⊻",
  vert: "∣",
  Vert: "∥",
  Vvdash: "⊪",
  wedge: "∧",
  weierp: "℘",
  wp: "℘",
  wr: "≀",
  xi: "ξ",
  Xi: "Ξ",
  yen: "¥",
  zeta: "ζ",
};

export const KATEX_ACCENTS = {
  acute: "ˊ",
  grave: "ˋ",
  ddot: "¨",
  tilde: "~",
  bar: "ˉ",
  breve: "˘",
  check: "ˇ",
  hat: "^",
  vec: "⃗",
  dot: "˙",
  mathring: "˚",
  "'": "ˊ",
  "`": "ˋ",
  "^": "ˆ",
  "~": "˜",
  "=": "ˉ",
  u: "˘",
  ".": "˙",
  c: "¸",
  r: "˚",
  v: "ˇ",
  H: "˝",
  textcircled: "◯",
} as Record<string, string>;

export const KATEX_FUNCTIONS = new Set<string>([
  "arccos",
  "arcctg",
  "arcsin",
  "arctan",
  "arctg",
  "arg",
  "ch",
  "cos",
  "cosec",
  "cosh",
  "cot",
  "cotg",
  "coth",
  "csc",
  "ctg",
  "cth",
  "deg",
  "dim",
  "exp",
  "hom",
  "ker",
  "lg",
  "ln",
  "log",
  "sec",
  "sh",
  "sin",
  "sinh",
  "tan",
  "tanh",
  "tg",
  "th",
]);

export type KatexNAryOp = { accent: string; limitLocationVal?: "subSup" };

export const KATEX_NARY_OPS: Record<string, KatexNAryOp> = {
  bigcap: { accent: "⋂" },
  bigcup: { accent: "⋃" },
  bigodot: { accent: "⨀" },
  bigoplus: { accent: "⨁" },
  bigotimes: { accent: "⨂" },
  bigsqcup: { accent: "⨆" },
  biguplus: { accent: "⨄" },
  bigvee: { accent: "⋁" },
  bigwedge: { accent: "⋀" },
  coprod: { accent: "∐" },
  intop: { accent: "∫" },
  prod: { accent: "∏" },
  smallint: { accent: "∫" },
  sum: { accent: "∑" },
};

export const KATEX_INTEGRAL_OPS: Record<string, KatexNAryOp> = {
  iiint: { accent: "∭", limitLocationVal: "subSup" },
  iint: { accent: "∬", limitLocationVal: "subSup" },
  int: { accent: "∫", limitLocationVal: "subSup" },
  oiiint: { accent: "∰", limitLocationVal: "subSup" },
  oiint: { accent: "∯", limitLocationVal: "subSup" },
  oint: { accent: "∮", limitLocationVal: "subSup" },
};

export const KATEX_LIMITS_TEXT_OPS = new Set<string>([
  "Pr",
  "det",
  "gcd",
  "inf",
  "lim",
  "liminf",
  "limsup",
  "max",
  "min",
  "sup",
]);
