/** KaTeX v0.16.22 — regenerate via `pnpm generate:katex` (fetches from https://raw.githubusercontent.com/KaTeX/KaTeX/v0.16.22/src). */
export const KATEX_ALIASES: Record<string, string> = {
  "bgroup": "{",
  "egroup": "}",
  "lq": "`",
  "rq": "'",
  "thinspace": ",",
  "medspace": ":",
  "thickspace": ";",
  "negthinspace": "!",
  "ordinarycolon": ":",
  "notni": "∌",
  "darr": "↓",
  "dArr": "⇓",
  "Darr": "⇓",
  "lang": "⟨",
  "rang": "⟩",
  "uarr": "↑",
  "uArr": "⇑",
  "Uarr": "⇑",
  "alef": "ℵ",
  "alefsym": "ℵ",
  "bull": "∙",
  "clubs": "♣",
  "Dagger": "‡",
  "diamonds": "♢",
  "empty": "∅",
  "exist": "∃",
  "harr": "↔",
  "hArr": "⇔",
  "Harr": "⇔",
  "hearts": "♡",
  "image": "ℑ",
  "infin": "∞",
  "isin": "∈",
  "larr": "←",
  "lArr": "⇐",
  "Larr": "⇐",
  "lrarr": "↔",
  "lrArr": "⇔",
  "Lrarr": "⇔",
  "plusmn": "±",
  "rarr": "→",
  "rArr": "⇒",
  "Rarr": "⇒",
  "real": "ℜ",
  "sdot": "⋅",
  "sect": "§",
  "spades": "♠",
  "sub": "⊂",
  "sube": "⊆",
  "supe": "⊇",
  "thetasym": "ϑ",
  "weierp": "℘"
};

export const KATEX_ACCENTS: Record<string, string> = {
  "acute": "ˊ",
  "grave": "ˋ",
  "ddot": "¨",
  "tilde": "~",
  "bar": "ˉ",
  "breve": "˘",
  "check": "ˇ",
  "hat": "^",
  "vec": "⃗",
  "dot": "˙",
  "mathring": "˚",
  "'": "ˊ",
  "`": "ˋ",
  "^": "ˆ",
  "~": "˜",
  "=": "ˉ",
  "u": "˘",
  ".": "˙",
  "c": "¸",
  "r": "˚",
  "v": "ˇ",
  "H": "˝",
  "textcircled": "◯"
};

export const KATEX_FUNCTIONS = new Set<string>(["Pr","arccos","arcctg","arcsin","arctan","arctg","arg","ch","cos","cosec","cosh","cot","cotg","coth","csc","ctg","cth","deg","det","dim","exp","gcd","hom","inf","ker","lg","lim","liminf","limsup","ln","log","mathop","max","min","sec","sh","sin","sinh","sup","tan","tanh","tg","th"]);

/** KaTeX macro-only symbols mapped to Unicode for Word OMML text runs. */
export const KATEX_SYMBOL_OVERRIDES: Record<string, string> = {
  "quad": " ",
  "qquad": "  ",
  "cdotp": "⋅",
  "neq": "≠",
  "notin": "∉",
  "perp": "⊥",
  "notni": "∌",
  "ulcorner": "⌜",
  "urcorner": "⌝",
  "llcorner": "⌞",
  "lrcorner": "⌟",
  "copyright": "©",
  "textregistered": "®",
  "vdots": "⋮",
  "dblcolon": "∷",
  "eqcolon": "∹",
  "coloneqq": "≔",
  "eqqcolon": "≕",
  "Coloneqq": "⩴",
  "llbracket": "⟦",
  "rrbracket": "⟧",
  "lBrace": "⦃",
  "rBrace": "⦄",
  "ne": "≠",
  "cdots": "⋯"
};
